# Generated by Django 5.1.1 on 2024-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardapp", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
