# Generated by Django 5.1.1 on 2024-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardapp", "0003_customuser_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
