# Generated by Django 5.1.1 on 2024-09-30 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardapp", "0004_customuser_is_active_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_email",
                        message="이메일 주소에는 정확히 하나의 @ 문자가 포함되어야 합니다.",
                        regex="^[^@]+@[^@]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
