# Generated by Django 5.1.1 on 2024-10-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardapp", "0005_alter_customuser_email_alter_customuser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
